# Generated by Django 5.1.4 on 2024-12-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='media/')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('reservada', models.BooleanField(default=False)),
            ],
        ),
    ]
