# Generated by Django 5.1.4 on 2024-12-25 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubanpulseproyect', '0004_paquete_direccion_paquete_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='paquete',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='paquete',
            name='reservada',
        ),
    ]
