# Generated by Django 5.1.4 on 2024-12-25 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubanpulseproyect', '0005_remove_paquete_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alojamientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_habitaciones', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Viajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=100)),
                ('cantidad_personas', models.IntegerField()),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='paquete',
            name='precio',
        ),
        migrations.CreateModel(
            name='Reservaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('fecha_entrada', models.DateField(max_length=100)),
                ('fecha_salida', models.DateField(max_length=100)),
                ('transporte', models.BooleanField(default=False)),
                ('comidas', models.CharField(max_length=100)),
                ('celulares', models.BooleanField(default=False)),
                ('otros_servicios', models.TextField(blank=True)),
                ('alojamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubanpulseproyect.alojamientos')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaciones', to='cubanpulseproyect.paquete')),
                ('viajes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubanpulseproyect.viajes')),
            ],
        ),
    ]
