# Generated by Django 5.1.4 on 2024-12-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubanpulseproyect', '0006_alojamientos_viajes_remove_paquete_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='precio',
            field=models.FloatField(null=True),
        ),
    ]
