# Generated by Django 5.1.4 on 2024-12-26 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubanpulseproyect', '0010_alter_alojamientos_reservado'),
    ]

    operations = [
        migrations.AddField(
            model_name='alojamientos',
            name='paquete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alojamiento', to='cubanpulseproyect.paquete'),
        ),
    ]
