# Generated by Django 5.1.4 on 2024-12-26 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubanpulseproyect', '0012_remove_reservaciones_alojamiento_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alojamientos',
        ),
    ]
