# Generated by Django 5.1.4 on 2024-12-27 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubanpulseproyect', '0014_remove_reservaciones_paquete_alojamientos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alojamientos',
            name='paquete',
        ),
        migrations.DeleteModel(
            name='Reservaciones',
        ),
        migrations.DeleteModel(
            name='Viajes',
        ),
        migrations.DeleteModel(
            name='Alojamientos',
        ),
        migrations.DeleteModel(
            name='Paquete',
        ),
    ]
