# Generated by Django 5.1.4 on 2024-12-27 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubanpulseproyect', '0016_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alojamiento',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='paquete',
            name='alojamiento',
        ),
        migrations.RemoveField(
            model_name='paquete',
            name='servicios',
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
        migrations.DeleteModel(
            name='Alojamiento',
        ),
        migrations.DeleteModel(
            name='Paquete',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
