# Generated by Django 5.1.4 on 2024-12-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubanpulseproyect', '0019_remove_paquete_alojamiento_remove_paquete_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alojamiento',
            fields=[
                ('nombre', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=1500)),
                ('precio', models.FloatField()),
                ('pedido', models.BooleanField(default=False)),
                ('tipo', models.CharField(max_length=50)),
                ('cant_habitaciones', models.IntegerField()),
                ('imagen', models.ManyToManyField(related_name='alojamiento', to='cubanpulseproyect.imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('nombre', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('precio', models.FloatField()),
                ('alojamiento', models.ManyToManyField(related_name='paquete', to='cubanpulseproyect.alojamiento')),
                ('imagen', models.ManyToManyField(related_name='paquete', to='cubanpulseproyect.imagen')),
                ('servicios', models.ManyToManyField(related_name='paquete', to='cubanpulseproyect.servicio')),
            ],
        ),
    ]
