# Generated by Django 5.1.4 on 2024-12-27 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubanpulseproyect', '0020_alojamiento_paquete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paquete',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
