# Generated by Django 5.1.4 on 2025-01-05 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubanpulseproyect', '0022_servicio_paquete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paquete',
        ),
    ]
