# Generated by Django 5.1.4 on 2025-01-05 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubanpulseproyect', '0024_paquete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete',
            name='servicios',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
