# Generated by Django 5.1.4 on 2025-01-06 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubanpulseproyect', '0026_servicio_paquete_servicios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete',
            name='servicios',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
