# Generated by Django 5.1.4 on 2025-01-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubanpulseproyect', '0030_servicio_paquete_servicios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='cant_dias',
            field=models.IntegerField(null=True),
        ),
    ]
