# Generated by Django 5.1.4 on 2025-01-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubanpulseproyect', '0032_remove_servicio_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='cant_dias',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
