# Generated by Django 5.1.4 on 2025-01-06 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubanpulseproyect', '0033_alter_servicio_cant_dias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete',
            name='hospedaje',
        ),
        migrations.DeleteModel(
            name='Alojamiento',
        ),
    ]
