# Generated by Django 5.1.4 on 2025-01-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubanpulseproyect', '0034_remove_paquete_hospedaje_delete_alojamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alojamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=1500)),
                ('precio', models.FloatField()),
                ('pedido', models.BooleanField(default=False)),
                ('tipo', models.CharField(max_length=50)),
                ('cant_habitaciones', models.IntegerField()),
                ('imagen', models.ManyToManyField(related_name='alojamiento', to='cubanpulseproyect.imagen')),
            ],
        ),
        migrations.AddField(
            model_name='paquete',
            name='hospedaje',
            field=models.ManyToManyField(related_name='paquete', to='cubanpulseproyect.alojamiento'),
        ),
    ]
