# Generated by Django 5.1.4 on 2025-01-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubanpulseproyect', '0035_alojamiento_paquete_hospedaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='tipo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
