# Generated by Django 5.1.4 on 2025-01-07 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubanpulseproyect', '0037_remove_servicio_cant_dias_remove_servicio_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete',
            name='servicios',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
