# Generated by Django 5.1.4 on 2025-01-07 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubanpulseproyect', '0039_servicio_paquete_servicios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paquete',
        ),
    ]
