# Generated by Django 5.1.4 on 2025-01-07 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubanpulseproyect', '0041_paquete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cliente', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('precio_total', models.FloatField(default=0.0)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubanpulseproyect.paquete')),
            ],
        ),
    ]
