# Generated by Django 5.1.4 on 2025-01-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubanpulseproyect', '0042_reservacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservacion',
        ),
    ]
