# Generated by Django 5.1.4 on 2025-01-10 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubanpulseproyect', '0043_delete_reservacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamiento',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(upload_to='media/')),
                ('alojamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubanpulseproyect.alojamiento')),
            ],
        ),
    ]
