# Generated by Django 5.1.4 on 2025-01-10 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubanpulseproyect', '0044_alter_alojamiento_precio_alter_paquete_precio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alojamiento',
            old_name='pedido',
            new_name='lleno',
        ),
    ]
