# Generated by Django 5.1.4 on 2025-01-10 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubanpulseproyect', '0045_rename_pedido_alojamiento_lleno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Habitacion',
        ),
    ]
