# Generated by Django 5.1.4 on 2025-01-10 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubanpulseproyect', '0049_alter_habitacion_disponible'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Habitacion',
        ),
    ]
