# Generated by Django 5.1.4 on 2025-01-10 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubanpulseproyect', '0050_delete_habitacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alojamiento',
            name='cant_habitaciones',
        ),
    ]
