# Generated by Django 5.1.4 on 2025-01-11 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubanpulseproyect', '0052_remove_paquete_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete',
            name='duracion_dias',
        ),
        migrations.RemoveField(
            model_name='paquete',
            name='duracion_noches',
        ),
    ]
