# Generated by Django 5.1.4 on 2025-01-11 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubanpulseproyect', '0058_remove_reserva_alojamiento_reserva_alojamientos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
