# Generated by Django 5.1.4 on 2025-01-13 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubanpulseproyect', '0060_reserva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alojamiento',
            old_name='lleno',
            new_name='reservado',
        ),
    ]
