# Generated by Django 5.1.4 on 2025-01-16 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubanpulseproyect', '0062_disponibilidad_remove_alojamiento_reservado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alojamiento',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='paquete',
            name='hospedaje',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='alojamiento',
        ),
        migrations.DeleteModel(
            name='Disponibilidad',
        ),
        migrations.RemoveField(
            model_name='paquete',
            name='servicios',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='paquete',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='servicios',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
        migrations.DeleteModel(
            name='Alojamiento',
        ),
        migrations.DeleteModel(
            name='Paquete',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
