# Generated by Django 5.1.4 on 2025-01-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubanpulseproyect', '0064_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamiento',
            name='reservado',
            field=models.ManyToManyField(blank=True, related_name='alojamiento', to='cubanpulseproyect.disponibilidad'),
        ),
    ]
