# Generated by Django 5.1.4 on 2025-01-16 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubanpulseproyect', '0065_alter_alojamiento_reservado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alojamiento',
            name='reservado',
        ),
        migrations.DeleteModel(
            name='Disponibilidad',
        ),
    ]
