# Generated by Django 5.1.4 on 2025-01-16 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubanpulseproyect', '0066_remove_alojamiento_reservado_delete_disponibilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('disponible', models.BooleanField(default=True)),
                ('alojamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cubanpulseproyect.alojamiento')),
            ],
        ),
    ]
