# Generated by Django 5.1.4 on 2025-01-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubanpulseproyect', '0067_disponibilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechaOcupada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='disponibilidad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Disponibilidad',
        ),
    ]
